name: GitHub-Profile-3D-Contrib

on:
  schedule: # 10:00 JST == 22:00 BRL
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
          USERNAME: ${{ github.claudiotassis }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
